import qbs 1.0

QtcPlugin {
    name: "MesonProjectManager"

    Depends { name: "Qt.widgets" }
    Depends { name: "Utils" }

    Depends { name: "Core" }
    Depends { name: "CppTools" }
    Depends { name: "ProjectExplorer" }
    Depends { name: "QtSupport" }
    Depends { name: "app_version_header" }

    pluginRecommends: [
        "Designer"
    ]

    files: ['./ExeWrappers/mesontools.h',
        './ExeWrappers/mesonwrapper.cpp',
        './ExeWrappers/mesonwrapper.h',
        './ExeWrappers/ninjawrapper.h',
        './ExeWrappers/toolwrapper.cpp',
        './ExeWrappers/toolwrapper.h',
        './KitHelper/kitdata.h',
        './KitHelper/kithelper.h',
        './MachineFiles/machinefilemanager.cpp',
        './MachineFiles/machinefilemanager.h',
        './MachineFiles/nativefilegenerator.cpp',
        './MachineFiles/nativefilegenerator.h',
        './MesonActionsManager/mesonactionsmanager.cpp',
        './MesonActionsManager/mesonactionsmanager.h',
        './MesonInfoParser/buildoptions.h',
        './MesonInfoParser/mesoninfo.h',
        './MesonInfoParser/mesoninfoparser.h',
        './MesonInfoParser/parsers/buildoptionsparser.h',
        './MesonInfoParser/parsers/buildsystemfilesparser.h',
        './MesonInfoParser/parsers/common.h',
        './MesonInfoParser/parsers/infoparser.h',
        './MesonInfoParser/parsers/targetparser.h',
        './MesonInfoParser/target.h',
        './Project/BuildOptions/OptionsModel/arrayoptionlineedit.cpp',
        './Project/BuildOptions/OptionsModel/arrayoptionlineedit.h',
        './Project/BuildOptions/OptionsModel/buidoptionsmodel.cpp',
        './Project/BuildOptions/OptionsModel/buidoptionsmodel.h',
        './Project/BuildOptions/mesonbuildsettingswidget.cpp',
        './Project/BuildOptions/mesonbuildsettingswidget.h',
        './Project/BuildOptions/mesonbuildsettingswidget.ui',
        './Project/BuildOptions/mesonbuildstepconfigwidget.cpp',
        './Project/BuildOptions/mesonbuildstepconfigwidget.h',
        './Project/BuildOptions/mesonbuildstepconfigwidget.ui',
        './Project/OutputParsers/mesonoutputparser.cpp',
        './Project/OutputParsers/mesonoutputparser.h',
        './Project/OutputParsers/ninjaparser.cpp',
        './Project/OutputParsers/ninjaparser.h',
        './Project/ProjectTree/mesonprojectnodes.cpp',
        './Project/ProjectTree/mesonprojectnodes.h',
        './Project/ProjectTree/projecttree.cpp',
        './Project/ProjectTree/projecttree.h',
        './Project/mesonbuildconfiguration.cpp',
        './Project/mesonbuildconfiguration.h',
        './Project/mesonbuildsystem.cpp',
        './Project/mesonbuildsystem.h',
        './Project/mesonprocess.cpp',
        './Project/mesonprocess.h',
        './Project/mesonproject.cpp',
        './Project/mesonproject.h',
        './Project/mesonprojectimporter.cpp',
        './Project/mesonprojectimporter.h',
        './Project/mesonprojectparser.cpp',
        './Project/mesonprojectparser.h',
        './Project/mesonrunconfiguration.cpp',
        './Project/mesonrunconfiguration.h',
        './Project/ninjabuildstep.cpp',
        './Project/ninjabuildstep.h',
        './Settings/General/generalsettingspage.cpp',
        './Settings/General/generalsettingspage.h',
        './Settings/General/generalsettingswidget.cpp',
        './Settings/General/generalsettingswidget.h',
        './Settings/General/generalsettingswidget.ui',
        './Settings/General/settings.cpp',
        './Settings/General/settings.h',
        './Settings/Tools/KitAspect/mesontoolkitaspect.cpp',
        './Settings/Tools/KitAspect/mesontoolkitaspect.h',
        './Settings/Tools/KitAspect/ninjatoolkitaspect.cpp',
        './Settings/Tools/KitAspect/ninjatoolkitaspect.h',
        './Settings/Tools/KitAspect/toolkitaspectwidget.cpp',
        './Settings/Tools/KitAspect/toolkitaspectwidget.h',
        './Settings/Tools/toolitemsettings.cpp',
        './Settings/Tools/toolitemsettings.h',
        './Settings/Tools/toolitemsettings.ui',
        './Settings/Tools/toolsmodel.cpp',
        './Settings/Tools/toolsmodel.h',
        './Settings/Tools/toolssettingsaccessor.cpp',
        './Settings/Tools/toolssettingsaccessor.h',
        './Settings/Tools/toolssettingspage.cpp',
        './Settings/Tools/toolssettingspage.h',
        './Settings/Tools/toolssettingswidget.cpp',
        './Settings/Tools/toolssettingswidget.h',
        './Settings/Tools/toolssettingswidget.ui',
        './Settings/Tools/tooltreeitem.cpp',
        './Settings/Tools/tooltreeitem.h',
        './Tests/testmesoninfoparser.cpp',
        './Tests/testmesonparser.cpp',
        './Tests/testmesonwrapper.cpp',
        './Tests/testninjaparser.cpp',
        './mesonpluginconstants.h',
        './mesonprojectplugin.cpp',
        './mesonprojectplugin.h',
        './versionhelper.h']
}
